apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: gke-codefresh-non-prod-us-east1-runtime-team
spec:
  destination:
    namespace: default
    server: https://34.138.204.227
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,kind-byoa-managed-cluster-gke-codefresh-non-prod-us-east1-runtime-team-cm.yaml,runtimes/kind-byoa/**/*.yaml,runtimes/kind-byoa/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/oleksandr-codefresh/helm-01.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
