apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: helm-01
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {ago2133/integration.config.yaml,ago2133/integration.secret.yaml,all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,configurations/**/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,helm-01/broken.yaml,helm-01/cf-gitops-runtime.yaml,helm-01/eks-local.yaml,helm-01/eks-private.yaml,helm-01/gs-permissions.yaml,runtimes/helm-01/**/*.yaml,runtimes/helm-01/*.yaml,sdssadasd/integration.config.yaml,sdssadasd/integration.secret.yaml,test/integration.config.yaml,test/integration.secret.yaml,tssss/integration.config.yaml,tssss/integration.secret.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/oleksandr-codefresh/helm-01.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
