gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      accountId: 67bca12b5e470fc3eecfdfb7
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        enabled: false
      ingressUrl: http://local.codefresh.io:8080
      name: kind-local
      isConfigurationRuntime: true
  argo-cd:
    global:
      image:
        repository: xeonalex/personal-argocd-dev
        tag: 3.0.3-dest-val-0
    acrController:
      enabled: true
  installer:
    skipValidation: false
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
