apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dsdsd
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/testcodefresh/argocd-example-apps.git
    path: helm-guestbook
    targetRevision: master
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: helm-01
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
