apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gs-permissions
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/xeonalex/handy-todo-extension.git
      path: git-source
      targetRevision: git-source
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: helm-01
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
