apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: aaaa
spec:
  promotionFlows:
    - name: demo
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - sss