apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: sdsd
spec:
  promotionFlows:
    - name: demo-retry
      gitTriggerSelectors:
        - key: commitMessage
          operator: NotIn
          values:
            - dsdsd
