apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: test
spec:
  promotionFlows:
    - name: to-prod
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - dssddsssccccc
