apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true 
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: cf-runtime-app-project
  source:
    repoURL: https://github.com/oleksandr-codefresh/helm-01.git
    targetRevision: HEAD
    path: resources/rt-byoa/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
