apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-vc1-rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://codefresh-io.github.io/argo-helm
    targetRevision: 2.37.3-7-v1.7.2-cap-OSS-697
    helm:
      releaseName: argo-rollouts
  destination:
    namespace: default
    server: https://alex-vc1-vcluster.rnd-sandbox.cf-infra.com
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
