gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      accountId: 67bca12b5e470fc3eecfdfb7
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        enabled: false
      ingressUrl: http://runtimes.local.com:7711
      name: rt-fork
      isConfigurationRuntime: true
  installer:
    skipValidation: false
  argo-cd:
    configs:
      cm:
        accounts.admin: apiKey,login
      params:
        server.insecure: true
        server.basehref: /argocd
        server.rootpath: /argocd
        controller.log.level: debug
    extraObjects:
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTP
            nginx.ingress.kubernetes.io/rewrite-target: /
          name: runtime-secondary-ingress
        spec:
          ingressClassName: nginx
          rules:
            - http:
                paths:
                  - backend:
                      service:
                        name: argocd-server
                        port:
                          number: 80
                    path: /sources-server
                    pathType: Prefix
                  - backend:
                      service:
                        name: internal-router
                        port:
                          number: 80
                    path: /repo-server
                    pathType: Prefix
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTP
          name: runtime-ingress
        spec:
          ingressClassName: nginx
          rules:
            - http:
                paths:
                  - backend:
                      service:
                        name: argocd-server
                        port:
                          number: 80
                    path: /argocd
                    pathType: Prefix
                  - backend:
                      service:
                        name: internal-router
                        port:
                          number: 80
                    path: /webhooks
                    pathType: Prefix
                  - backend:
                      service:
                        name: internal-router
                        port:
                          number: 80
                    path: /workflows
                    pathType: Prefix
                  - backend:
                      service:
                        name: internal-router
                        port:
                          number: 80
                    path: /app-proxy
                    pathType: Prefix
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
