gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      accountId: 67bca12b5e470fc3eecfdfb7
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        enabled: false
      ingressUrl: http://runtimes.local.com:7711
      name: rt-fork
  installer:
    skipValidation: false
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
