apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-git-source
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/oleksandr-codefresh/helm-01.git
      path: git-sources/rt-fork/default
      targetRevision: HEAD
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: rt-fork
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
