apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rt-fork-release
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/oleksandr-codefresh/helm-01.git
    targetRevision: HEAD
    path: resources/rt-fork/chart
    helm:
      releaseName: rt-fork-release
  destination:
    namespace: rt-fork
    server: https://kubernetes.default.svc
  # syncPolicy:
  #   automated:
  #     allowEmpty: true
  #     prune: true
  #     selfHeal: true
