apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: degraded-wrong-image
 labels:
   commit: test
 finalizers:
   - resources-finalizer.argocd.argoproj.io/foreground
spec:
 project: default
 source:
   path: degraded/wrong-image
   repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
   targetRevision: personal-eks
 destination:
   name: in-cluster
   namespace: test-dev
 syncPolicy:
   automated:
     allowEmpty: true
     prune: true
     selfHeal: true
   retry:
     limit: 2
     backoff:
       duration: 5s
       maxDuration: 3m0s
       factor: 2
   syncOptions:
     - PrunePropagationPolicy=foreground
     - Replace=false
     - PruneLast=false
     - Validate=true
     - CreateNamespace=true
     - ApplyOutOfSyncOnly=false
