apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guesbook-roll-multi
  annotations: 
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
    - path: multi-source/canary-rollout/part-one
      repoURL: https://github.com/testcodefresh/argocd-example-apps
      targetRevision: test-alex-03-07-25
    - path: multi-source/canary-rollout/part-two
      repoURL: https://github.com/testcodefresh/argocd-example-apps
      targetRevision: test-alex-03-07-26
  destination:
    name: in-cluster
    namespace: multi-test-dev
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
