apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: just-delete
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: prod
      dependsOn:
        - dev
      policy:
        action: pr
