apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: to-prod
  annotations:
    description: dsdsd
spec:
  triggerEnvironment: dev
  steps:
    - environment: prod
      dependsOn:
        - dev
      policy:
        action: pr
