gitops-runtime:
  app-proxy:
    config:
      argoCdUrl: http://argo-cd-server:80/argocd
    env:
      CORS: >-
        http://local.codefresh.io,https://g.codefresh.io,https://sandbox-1.codefresh.io,https://sandbox-2.codefresh.io,https://sandbox-3.codefresh.io
  argo-cd:
    enabled: false
  gitops-operator:
    enabled: true
  global:
    codefresh:
      accountId: 67bca12b5e470fc3eecfdfb7
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    external-argo-cd:
      configs:
        tls:
          certificates: {}
      passwordSecretKeyRef:
        key: password
        name: argocd-initial-admin-secret
      redis:
        port: 6379
        svc: argocd-redis
      repoServer:
        port: 8081
        svc: argocd-repo-server
      server:
        port: 80
        protocol: http
        svc: argocd-server
        rootpath: /argocd
      username: admin
    runtime:
      ingress:
        className: nginx-public
        enabled: true
        hosts:
          - alex-byoa.rnd.sandbox.codefresh.io
        skipValidation: true
      name: byoa
      isConfigurationRuntime: true
