gitops-runtime:
  app-proxy:
    env:
      CORS: >-
        http://local.codefresh.io,https://g.codefresh.io,https://sandbox-1.codefresh.io,https://sandbox-2.codefresh.io,https://sandbox-3.codefresh.io
  argo-cd:
    enabled: false
  gitops-operator:
    enabled: true
  cf-argocd-extras:
    eventReporter:
      container:
        image:
          registry: docker.io
          repository: xeonalex/cf-argocd-extras
          tag: delete-event-0
    # sourcesServer:
    #   container:
    #     image:
    #       registry: docker.io
    #       repository: xeonalex/cf-argocd-extras
    #       tag: v3-health-status-1
  global:
    codefresh:
      accountId: 67bca12b5e470fc3eecfdfb7
      url: https://86792f8be875e7bd.gost.shared-services.cf-infra.com
      url2: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    external-argo-cd:
      configs:
        tls:
          certificates: {}
      passwordSecretKeyRef:
        key: password
        name: argocd-initial-admin-secret
      redis:
        port: 6379
        svc: argocd-redis
      repoServer:
        port: 8081
        svc: argocd-repo-server
      server:
        port: 80
        protocol: http
        svc: argocd-server
        rootpath: /argocd
      username: admin
    runtime:
      ingress:
        className: nginx-public
        enabled: true
        hosts:
          - alex-byoa.rnd.sandbox.codefresh.io
        skipValidation: true
      name: byoa
      isConfigurationRuntime: false
