apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.15.1
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh/dev
    # version: 0.15.1
    version: 0.0.0-chore-cr-26738-argo-cd-2.13.3-9055e32
