gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 65a57fa5f5681104cb83078f
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - alex-hermes-local.rnd-sandbox.cf-infra.com
        protocol: https
      name: helm-01
  installer:
    skipValidation: true
