gitops-runtime:
  app-proxy:
    replicaCount: 0
    config:
      cors: http://local.codefresh.io
  #  argo-workflows:
  #    controller:
  #      replicas: 1
  argo-cd:
    # configs:
    #   cm:
    #     codefresh.reporterVersion: v2
    eventReporter:
      enabled: "true"
      version: v2
      env: 
        - name: USE_GRPC
          value: "true"
    repoServer:
      replicas: 1
    controller:
      replicas: 1
    server:
      replicas: 1
        # image:
        repository: docker.io/xeonalex/personal-argocd-dev
      tag: vuln-fix
      service:
        # annotations:
        #   kubernetes.io/ingress.class: nginx-public
        type: LoadBalancer
  event-reporters:
    workflow:
      eventSource:
        replicas: 0
      sensor:
        replicas: 0
  global:
    codefresh:
      accountId: 65a57fa5f5681104cb83078f
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - alex-hermes-local.rnd-sandbox.cf-infra.com
        protocol: https
      name: helm-01
  installer:
    skipValidation: true
