gitops-runtime:
  app-proxy:
    replicaCount: 1
    config:
      cors: http://local.codefresh.io
      argoCdUrl: http://argo-cd-server:80/argocd
  argo-workflows:
    controller:
      podGCDeleteDelayDuration: 300s
  argo-cd:
    configs:
      params:
        server.basehref: /argocd
        server.rootpath: /argocd
      cm:
        codefresh.reporterVersion: v2
    eventReporter:
      enabled: 'true'
      version: v2
      replicas: 1
    repoServer:
      replicas: 1
      volumes:
        - configMap:
            name: helm-sops-config
          name: cmp-plugin
    controller:
      replicas: 1
    server:
      replicas: 1
  event-reporters:
    events:
      argoCDServerServicePort: 80/argocd
  gitops-operator:
    env:
      ARGO_CD_URL: argo-cd-server:80/argocd
  global:
    codefresh:
      accountId: 65c5f89ca4bb5cd2c5d9c415
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-public
        enabled: true
        hosts:
          - alex-hermes-local.rnd.sandbox.codefresh.io
        protocol: https
      name: helm-01
      isConfigurationRuntime: true
  installer:
    skipValidation: true
