# helm install my-kube-prometheus-stack oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack:77.1.0
# helm show values oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack:77.1.0 > values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/prometheus-community/charts
    chart: kube-prometheus-stack
    targetRevision: 77.1.0
    helm:
      values: |
        nodeExporter:
          enabled: false
        prometheus-node-exporter:
          prometheus:
            monitor:
              interval: 10s
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true