apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      alex-app-generator:argoproj.io/Application:codefresh/ar-10-to-arena-11-app-1-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    app.kubernetes.io/instance: alex-app-generator
    cf.load-test: 'true'
  name: sync-issue-main-2-prod
spec:
  destination:
    name: in-cluster
    namespace: scale-test
  project: default
  source:
    path: prod
    repoURL: https://github.com/oleksandr-codefresh/argo-load-product-1
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
