apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.22.2
dependencies:
  - name: gitops-runtime
    # repository: oci://quay.io/codefresh
    # version: 0.22.2
    repository: oci://quay.io/codefresh/dev
    version: 0.0.0-cr-test-queue-12dafa4
