gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
  argo-cd:
    configs:
      cm:
        application.instanceLabelKey: argocd.argoproj.io/instance
        application.resourceTrackingMethod: annotation
  event-reporters:
    workflow:
      serviceAccount:
        name: codefresh-sa
  global:
    codefresh:
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx
        enabled: true
        hosts:
          - alex.cd-team.cf-cd.com
        protocol: https
      name: helm-01
