gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
      graphqlPlayground: "true"
#  argo-workflows:
#    controller:
#      replicas: 1
  argo-cd:
    configs:
      cm:
        application.instanceLabelKey: argocd.argoproj.io/instance
        application.resourceTrackingMethod: annotation
    repoServer:
      replicas: 1
    controller:
      replicas: 1
    server:
      replicas: 1
      # image:
        # repository: docker.io/xeonalex/personal-argocd-dev
        # tag: 2.8.1-parrallel-events-23
      service:
        type: LoadBalancer
  event-reporters:
    workflow:
      eventSource:
        replicas: 0
      sensor:
        replicas: 0
      serviceAccount:
        name: codefresh-sa
  global:
    codefresh:
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx
        enabled: true
        hosts:
          - alex.cd-team.cf-cd.com
        protocol: https
      name: helm-01
