kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dock-test
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: dock-test
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: dock-test
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgALjGYB4hCju1sWkP/ng5VqktvY5+0zBw2wpynfTZu6DXk5UQNfL/HfkxxK7uB3ykg7py6mc6K3IO6wyBeQ29/uQwEFil2aMrqX4hQxnT1GPX01ZX4oCkNjfqjlPk02XyNu+WxWo4as2WRmXi6yUOEn7FdotcAwf8c7gYKyy/LP9d53qYNwhDxVuKe7OpxAqlFW98AEHvRQDe0XmRIQyW5RcnQA/uvDMNVkBoiGNQ1ZTxL+tCkzCQlRWYJviGuztpWy0tLmiqu64PstYAA1xIpjQpJ34YsYgQn6GiiP+px+rs0CjfrDIEClMjBHElgkWRThiEYCj2AmHfVaEKNPywOPTtkg2yzPayhj130iXMcmcF/8PyNEmg/7P+LzAJONUuZzZduuUiEoPyn9rV1LT4dm+N1E3TSEv7xXVizRAzsWntYbCPjTdkamk43Ud5wJQJclf2lvy/NFfVsfKkoWuPHj196pN2qFLUf7MTg4J2q1tLqjwR+BVc7xuhxt24TsTZSmk1D1/0HtjqsAeksAOcRAL0U/e2X0suYaFFracAIU9z/PQGRjW310CfnoRgZ9dGkgZfK+NGaWJTQUbLOMYIFM1G4rjyVI2hqlAlDGj96Of6AhdDXKQApDFVDIRvONrWjmhlr0PwG7Z4nhTe+DXk5BimDOUz7guSASHiEOiyprwm4VFM+QWWR/hNhBxmkc5xx8lUq6fHKBIJuUrQzg2IfDqqnL9Vwv7yQ+
