kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dock-test
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: dock-test
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: dock-test
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgCTGtvo5r+4m+TmLW0/esI9A6blfwuLkdJqQqcGC1Q7IVMz0giAy956G/hFmpKUEshjTOmhYWo0CH1NsxicCCOp2VThosatWxj0ItJO/f+SqrwuhY0O8W14fYVr7YJASdRgWB2mxVPk0znynEByGa6wwGKZVL5Bu2kj7CpZIG9TFMtZKNejgQSvvuDNU03R3DNC1fEzIj8XQfcyLV7sN8q2aTb7CSHp44YvfDxEf2nAIOu0USFlj/OgNHnGAp6Mvx6ae+6DqJd6D0/3yVunH4aPYsV1TGiAgjeObkZhAGwYYsfGWjiSJ8NMTdMUgyVKPxI5nwMz9OUD3972EC7no477JXv+WafHZmWhv6slOZ6e0luvoaniPZ2873jKCsjviAx0QxI+/oAHsVsjJjMKsvjuLAMWDt7iISz7DDRF8DgDoCh2XMooq/Fxwipx0grYLJHM4XlsQizrQQ8qgcVh/sUmMTRUwAJxDFE/tZ+/ZZtTwH6/oh3OS6CyqTzOBQEQksyO4H7t/LaPIoPAa7uWaPmsIVb9OX0KdkmcJqUzRQNpKG4etLD6sDvV4rYpaZkmfyudCNUCYooEEYpE+jpwm3U91Uh9P/R5mvHMEr6DBaeQgpsI43Sumh26orgLSTkwODuLfC/7DgqFvuEYzC9hAabtLotAcnJfSa6eajbhKo4Nnrwafq8yoeLogF+kJoiVsSRY1+r4ZfIpJBw4KbDWA8A=
