kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: gfdgdfgdfv
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: gfdgdfgdfv
    codefresh.io/integration-type: registry.ghcr
spec:
  template:
    metadata:
      name: gfdgdfgdfv
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgBtDsDRnMnT1N9RJgwKPEAvbpwiDCtJvl5a90CB9FxlAkS4ffghvhUx8KqNAemyhCP9ZwRLvDrpRIXzIgyYaDbW/yWiSyZQBvVvJ1ssbfkyRb+h/HFWHIL4XN6zQ5MkpiPSZDzm5JtzccXyV3Z2FVRnIUQl+64wYMybmOhgUCToXKs0H2zsKZRsuS55/aoXMIrKHMLrLuRzbRFdsHnbFnoF1lBLTQhiYoxfl/0O32GfHn75Ufq8p5hiC76maNct1nrXFYK9h7LYxxwUi28OIM9Ko/qO2aU2Gr+DqG8k5YNUcHS/mbteOZfdOFoJpeRLydU7RaLg1WVtTm3Si2/I1cJCPugfT/IoR87k6uMTHyoD2rxfFrN9Aqi5/19jCyGvg7DvkHh/93ACyiVjsZRSlQ/cgroS1ZZfs4P+pigBu6Bp2ZjE2KZ/tiOGd6KqYNPKCRnNbHO7+0OVPPFL3I/pdozfvu0aGxyY8Ja64ENkSHnfOxVJL5m3Utd1Y13Uu03VQMBwewnpU03ASCMpZfbFQdLdRZpm5AaY3S+e23bbipWGFVR4vfGOhtvyDw4/D+LIJ7rXbv4NaGt0Eo9eEmXmwPJyYnVDez3lhhGCHopVlm4X5pxrV8mqz8jZoss6ornedCU3zSmoiF/o+3+FJKbAWkzjUvsBwDxG3afMM1TaumjHbRaLqgb6dpDFlw9enaBxQOV+HXDoMXwIZw==
