apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-unpriv2
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbooks
      release: helm-guesbook
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: helm-guesbook
    spec:
      containers:
        - image: xeonalex/guesbook-unprivileged:0.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
