gitops-runtime:
  app-proxy:
    replicaCount: 0
    config:
      cors: http://local.codefresh.io
      graphqlPlayground: 'true'
  argo-cd:
    enabled: false
  global:
    codefresh:
      accountId: 67bca12b5e470fc3eecfdfb7
      url: https://alexs-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    external-argo-cd:
      auth:
        type: token
        tokenSecretKeyRef:
          name: gitops-runtime-argo-cd-token
          key: token
      server:
        rootpath: /argocd
    runtime:
      ingress:
        enabled: false
      ingressUrl: http://byoa.local-kind.io:7777
      name: kind-byoa
  tunnel-client:
    enabled: false
