apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alina-rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/codefresh-io/csdp-official.git
    path: csdp/base_components/apps/argo-rollouts/_components/codefresh-base
    targetRevision: stable
  destination:
    namespace: default
    server: https://B2A8F47D84174C53308248C7BB3693A1.gr7.us-east-1.eks.amazonaws.com
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
