apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pysarenko-rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://codefresh-io.github.io/argo-helm
    targetRevision: 2.22.1-1-cap-sw
    helm:
      releaseName: argo-rollouts
  destination:
    namespace: default
    server: https://3FA5EA816DC898A85C8CE7ABAEF59850.gr7.us-east-1.eks.amazonaws.com
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
