apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broken
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/oleksandr-codefresh/eks-local_private-git-sourceff.git
      path: .dssd
      targetRevision: dsds
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
