apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: test
spec:
  priority: 1
  selector:
    product:
      names:
        - helm-guestbook
    targetEnvironment:
      names:
        - dev
  policy:
    action: pr
