apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action-labels-update
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
    description: echo-labels
spec:
  serviceAccountName: cf-default-promotion-workflows-sa
  entrypoint: echo
  templates:
    - name: echo
      steps:
        - - name: echo-labels
            template: echo-labels
        - - name: echo-step-1
            template: echo-step-1
        - - name: echo-step-2
            template: echo-step-2
    - name: echo-labels
      script:
        image: alpine
        command:
          - sh
        source: >
          set -eu

          apk add --no-cache jq >/dev/null

          echo '{{workflow.labels.json}}' | jq -r 'to_entries[] | "\(.key)=\(.value)"'
    - name: echo-step-1
      script:
        image: alpine
        command:
          - sh
        source: |
          echo "This is step 1"
    - name: echo-step-2
      script:
        image: alpine
        command:
          - sh
        source: |
          echo "This is step 2"
