apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: alex-app-generator
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valuesObject:
        clusters:
          - devApp: 50
            name: in-cluster
            prodApp: 1
        runtimeName: rt-fork
    path: arena-app-generator
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true