apiVersion: codefresh.io/v1beta1
kind: RestrictedGitSource
metadata:
  name: test
spec:
  source:
    repoURL: https://github.com/oleksandr-codefresh/eks-local_git-source.git
    path: kind-byoa-gs-restricted
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destinations:
  - server: https://kubernetes.default.svc
    namespace: test-dev
    name: in-cluster
  - server: '*'
    namespace: '*'
    name: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  sourceRepos:
  - '*'
  sourceNamespace: cf-apps
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
