apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,byoa/boya-gs-private.yaml,byoa/byoa-git-source-2.yaml,byoa/byoa-permissions-gs.yaml,byoa/cf-gitops-runtime.yaml,byoa/ue1-e2e-rollout-reporter.yaml,byoa/ue1-e2e-rollouts.yaml,configurations/**/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,runtimes/byoa/**/*.yaml,runtimes/byoa/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/oleksandr-codefresh/helm-01.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
