apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: ue1-e2e
spec:
  destination:
    namespace: default
    server: https://2460939F368460F5FACBF11FADEA0D79.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,byoa-managed-cluster-ue1-e2e-cm.yaml,runtimes/byoa/**/*.yaml,runtimes/byoa/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/oleksandr-codefresh/helm-01.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
