kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: ago2133
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: ago2133
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: ago2133
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    api_token: >-
      AgAFFlLvEpCCW4UErlnwRkOlY7tK4JDvWRdKsd6ses0eaMiotaiCAyNHGvgMbE/D6z6Vp/FTq15ToaAkUYAAYtBxSbcdtiObNqqyvVQtEqboKJVrBd7BBmInYaCL3ruuMpH4RntR4G83hVgjHQs/+5gsj/rDM3e2RuO8KOctCs5VuwGQSmAwKQNQGwYrpj2EGcCBmTfF00chyaYrbGo2QvSS8OgjUgcHm9w8D7iQZOT0Du7Dfey/J9nz/TZAy/4nKAyBhTRnZkMiBDrZ1LRDgtpGbXvzdumljOLk30j7kGqyl0lixZeDkY/vsGfM7K2vs6Ae/CP6hJN24vDJgvsqC0x7y+/+x19sIkmJLHc7Hwo+OygO8Sk336AQT6le4Q5ID7+jZw5oZFfueinDDhpMzbcc2n+h7naurzvXkkKdNBeuYpP9vB+cn5qUuU5C8C79aDCsKAbhaKuxREh+2NL53+iyf+XjJEEBnnJSmdjHkRmilr3fZnr7DHUWAaMAnrASK4N5OQbBojh3aJlY6ItMRsoPxABblUIgMpgJzjreStSIRQmSf1zmfMlCfuiSm/1WCfmmurRp8DcTXe/gBj37qz61KKGqjyvbzoc2i73hXQGnxb+YDhmNf4uzM3LajljAZH7bLmObHN4idTnIz/br+T55E1aro7pepoKY5qGsZn0hObVsRcLcW/K+QY0t5INoSXqiy9Z6Xme8qQ==
