kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: new-docker
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: new-docker
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: new-docker
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgBRwWcjos3knbJGwmJt8gK4uU0mf11qOUYSL+/Jc3K/4yIfXxTF4FUOCGB5f6+LZ2OoRvLmuqvQL4vAWGKOeRF74k1ZHuoaIvMY9fPSX710Jah4FcPSLfwcSW6K5VaW/hJZ0dWOX57sBrkaGEPqVfYYJQNrMJF5kt9bO9JTBMR80MpbXsu4At9loZSepyYXzTuJOdYsUYb95fN+8jQDWf3L/L8LfcqvSTTTkc6l49kwT281dYdriFsNXCoTq8f+yOMfIZqRv9OetmbqnXIPJIBVFSmoT6yITZnJ0Or4bAxEoFN3Q4LXVyw8AFbwwUWiVQ3tmTathZk3JM0jjiO6wjocRhFZ83pyzxJy8FCtljUgvmsWWVgmtPRwjFhrFhUYhqQ6tfEB2zVxKqPXIkw05GWgdf0CWSfokMTtKiw7Fzd2Oh6cHxk6e4aNmESCeQzJckcOCMZAdhVeVfxjf+gzRUVdm5UJeAtnY+iK9e57fF6nmCWGq9P/Z7ZITrqFuJ6lSA285LBJQ5Qjn5+jWMX24L1Nh4ZmKK6LUs9ty5+RriogrLnrbhszajNE7CnKsMSwKn0hxAhytY3MmBlv/lOYi7dgzs96kfIVHawy0QaJgLThR7PlNkgbc1IZtOAu3/ZOFuCMT33izPTwO8rwHKDbFVemeERldXrgansNTGQs4mvaBxYK7rtGvojtfMgU6cEW/eQyKjiCtfc9zxoOGbI=
