apiVersion: v1
kind: ConfigMap
metadata:
  name: sdssadasd
  labels:
    codefresh.io/entity: integration-config
    codefresh.io/integration-type: issue.jira
data:
  host_url: https://atlassian.net
  email: ssssd@dsda.com
